### ISSUE TITLE
Build failed in Win10 Docker

### ISSUE THREAD

**Issue by owllyi** [topfreegames/xk6-pitaya#5]
Build Env:
Win10 X64, Docker Desktop

Build Command:
docker run --rm -it -e GOOS=windows -v "%cd%:/xk6" grafana/xk6 build --output k6.exe --with github.com/topfreegames/xk6-pitaya=. --with github.com/topfreegames/pitaya/v2=../

Error Info:

go: finding module for package github.com/topfreegames/pitaya/v2/session
go: finding module for package github.com/topfreegames/pitaya/v2/client
go: finding module for package github.com/topfreegames/pitaya/v2
go: finding module for package github.com/topfreegames/pitaya/v2/conn/message
k6 imports
github.com/topfreegames/pitaya/v2: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2
k6 imports
github.com/topfreegames/xk6-pitaya imports
github.com/topfreegames/pitaya/v2/client: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2/client
k6 imports
github.com/topfreegames/xk6-pitaya imports
github.com/topfreegames/pitaya/v2/conn/message: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2/conn/message
k6 imports
github.com/topfreegames/xk6-pitaya imports
github.com/topfreegames/pitaya/v2/session: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2/session

How can I solve this problem? Thanks~

**Comment by owllyi** [comment]
I've been running the build in the pitaya/xk6-pitaya directory, but it's not working. I even installed xk6 myself and executed it, but I'm still getting the same error.

D:\github\pitaya\xk6-pitaya>xk6 build --with github.com/topfreegames/xk6-pitaya=. --with github.com/topfreegames/pitaya/v2=../

**Comment by owllyi** [comment]
D:\Work\github\pitaya\xk6-pitaya>xk6 build --with github.com/topfreegames/xk6-pitaya=. --with github.com/topfreegames/pitaya/v2=../
2024/01/09 23:03:05 [INFO] Temporary folder: C:\Users\mac\AppData\Local\Temp\buildenv_2024-01-09-2303.469490676
2024/01/09 23:03:05 [INFO] Initializing Go module
2024/01/09 23:03:05 [INFO] exec (timeout=10s): C:\Program Files\Go\bin\go.exe mod init k6
go: creating new go.mod: module k6
2024/01/09 23:03:05 [INFO] Replace github.com/topfreegames/xk6-pitaya => D:\Work\github\pitaya\xk6-pitaya
2024/01/09 23:03:05 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod edit -replace github.com/topfreegames/xk6-pitaya=D:\Work\github\pitaya\xk6-pitaya
2024/01/09 23:03:05 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod tidy -compat=1.17
go: warning: "all" matched no packages
2024/01/09 23:03:05 [INFO] Replace github.com/topfreegames/pitaya/v2 => ../
2024/01/09 23:03:05 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod edit -replace github.com/topfreegames/pitaya/v2=../
2024/01/09 23:03:05 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod tidy -compat=1.17
go: warning: "all" matched no packages
2024/01/09 23:03:05 [INFO] Pinning versions
2024/01/09 23:03:05 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod tidy -compat=1.17
go: finding module for package github.com/topfreegames/pitaya/v2
go: found github.com/topfreegames/xk6-pitaya in github.com/topfreegames/xk6-pitaya v0.0.0-00010101000000-000000000000
go: finding module for package github.com/onsi/gomega
go: finding module for package github.com/topfreegames/pitaya/v2/conn/message
go: finding module for package github.com/topfreegames/pitaya/v2/client
go: finding module for package github.com/onsi/ginkgo
go: finding module for package github.com/topfreegames/pitaya/v2
go: finding module for package github.com/topfreegames/pitaya/v2/session
go: found github.com/onsi/ginkgo in github.com/onsi/ginkgo v1.16.5
go: found github.com/onsi/gomega in github.com/onsi/gomega v1.30.0
go: finding module for package github.com/topfreegames/pitaya/v2/session
go: finding module for package github.com/topfreegames/pitaya/v2/client
go: finding module for package github.com/topfreegames/pitaya/v2
go: finding module for package github.com/topfreegames/pitaya/v2/conn/message
go: k6 imports
        github.com/topfreegames/pitaya/v2: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2
go: k6 imports
        github.com/topfreegames/xk6-pitaya imports
        github.com/topfreegames/pitaya/v2/client: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2/client
go: k6 imports
        github.com/topfreegames/xk6-pitaya imports
        github.com/topfreegames/pitaya/v2/conn/message: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2/conn/message
go: k6 imports
        github.com/topfreegames/xk6-pitaya imports
        github.com/topfreegames/pitaya/v2/session: module github.com/topfreegames/pitaya/v2@latest found (v2.9.0, replaced by ../), but does not contain package github.com/topfreegames/pitaya/v2/session
2024/01/09 23:03:06 [INFO] Cleaning up temporary folder: C:\Users\mac\AppData\Local\Temp\buildenv_2024-01-09-2303.469490676
2024/01/09 23:03:06 [FATAL] exit status 1

**Comment by owllyi** [comment]
xk6 build --with github.com/topfreegames/xk6-pitaya=D:\Work\github\pitaya\xk6-pitaya --with github.com/topfreegames/pitaya/v2=D:\Work\github\pitaya

Just change it to the absolute path, is ok~

**Comment by rsafonseca** [comment]
Oh, i just realised you're in windows, good to know that it's sorted with absolute paths, I don't have a windows machine at hand to test but it might be as simple as using ..\ instead of ../ for the relative path in `github.com/topfreegames/pitaya/v2=..\`

**Comment by owllyi** [comment]
=..\ Still report an error
=%cd%\.. Is OK

**Comment by owllyi** [comment]
pitaya/xk6-pitaya 's code is not the latest version~

switch opts.Serializer {
	case "json":
		client.client = pitayaclient.New(logrus.InfoLevel)
		break
	case "protobuf":
		if opts.DocsRoute == "" {
			common.Throw(rt, errors.New("docsRoute is required when using protobuf serializer"))
		}
		client.client = pitayaclient.NewProto(opts.DocsRoute, logrus.InfoLevel)
		break
	default:
		fmt.Printf("Serializer %s not supported, using json serializer", opts.Serializer)
		client.client = pitayaclient.New(logrus.InfoLevel)
		break
	}

This code is lost.
